In [2]:
aList = ['Johe', 33 ,'ToronTo', True ]
aList

['Johe', 33, 'ToronTo', True]

In [4]:
bin_color=['Red','Green','Blue','Yellow']
bin_color[1]

'Green'

In [5]:
bin_color=['Red','Green','Blue','Yellow']

In [8]:
a = [1,2, [100,200,300],6]
max(a[2])

300

In [10]:
a[2][1]

200

In [12]:
bin_color=['Red','Green','Blue','Yellow']
for aColor in bin_color:
    print(aColor + ' Square')

Red Square
Green Square
Blue Square
Yellow Square


In [14]:
list(filter(lambda x : x > 100, [-5,200,300,-10,10,1000]))

[200, 300, 1000]

In [17]:
list(map(lambda x : x**2,[11,22,33,44,55]))

[121, 484, 1089, 1936, 3025]

In [20]:
from functools import reduce
def doSum(x1,x2):
    return x1 + x2

x = reduce(doSum, [100,122,33,4,5,6])

x

270

In [22]:
x =range(6)
list(x)

[0, 1, 2, 3, 4, 5]

In [26]:
oddNum = range(3,29,2)
list(oddNum)

[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27]

In [29]:
bin_color = ('Red','Green','Blue','Yellow')
bin_color[1]

'Green'

In [31]:
bin_color[:2]

('Red', 'Green')

In [33]:
bin_colors = {
    'manual_color' : 'Yellow',
    'approved_color' : 'Green',
    'refused_color' : 'Red'
}

bin_colors

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}

In [35]:
bin_colors.get('manual_color')

'Yellow'

In [37]:
bin_colors['manual_color']

'Yellow'

In [40]:
bin_colors['manual_color'] = 'Purple'
bin_colors

{'manual_color': 'Purple', 'approved_color': 'Green', 'refused_color': 'Red'}

In [42]:
green = {'grass', 'leaves'}
green

{'grass', 'leaves'}

In [44]:
green = {'grass', 'leaves','grass'}
green

{'grass', 'leaves'}

In [45]:
yellow = {'dandelions','fire hydrant','leaves'}
red = {'fire hydrant','blood','rose','leaves'}

In [49]:
yellow|red

{'blood', 'dandelions', 'fire hydrant', 'leaves', 'rose'}

In [51]:
yellow&red

{'fire hydrant', 'leaves'}

In [95]:
import pandas as pd
df = pd.DataFrame([['11','Fares',32,True],['2','Elena',23,False],['3','Steven',40,True]])
df.columns =['id','name','age','decision']

df

id    name  age  decision
0  11   Fares   32      True
1   2   Elena   23     False
2   3  Steven   40      True

In [96]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [97]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [98]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [103]:
df[(df.age < 35) & (df.decision ==True)]

id   name  age  decision
0  11  Fares   32      True

In [105]:
import numpy as np

In [108]:
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [110]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [112]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [114]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [116]:
print(type(myVector))

<class 'list'>


In [118]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [121]:
print(type(myVector))

<class 'numpy.ndarray'>
